apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: smartbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "smartbank"
            - name: POSTGRES_USER
              value: "smartbank"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartbank-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartbank-deployment
  namespace: smartbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartbank
  template:
    metadata:
      labels:
        app: smartbank
    spec:
      containers:
        - name: smartbank
          image: smartbank:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: smartbank-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartbank-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smartbank-secret
                  key: JWT_SECRET